title: not your naked truth
description:
 
copyright: @ajlkn
sass:
  sass_dir: assets/sass
url: http://teoryaclothing.com
disqus_shortname: stratajekylldemo
facebook_username: teoryaclothing
twitter_username: "#" teoryaclothing
linkedin_username: "#"
instagram_username: teoryaclothing
pinterest_username:
flickr_username:
github_username:  "#"
feed_icon: rss
email: "#"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
